server:
  port: 8086

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: test-group
    send-message-timeout: 3000
    retry-times: 3
  consumer:
    group: test

spring:
  data:
    mongodb:
      uri: mongodb://ljdll:ljdll@localhost:27017/ljdll?authSource=admin

mybatis-flex:
  datasource:
    dm8:
      driverClassName: dm.jdbc.driver.DmDriver
      url: jdbc:dm://localhost:5236/LJDLL?characterSet=UTF-8
      username: LJDLL
      password: LJDLL
